### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Malcanteth** [SyncGM/console#2]
Tested on empty project with just SES Console and (optionally) SES Core
Versions 1.0-1.2 do nothing
Versions 1.3+ just freeze the game

WinXP x86, RPGMaker VX Ace 1.02a (Steam)

**Comment by Solistra** [comment]
In RPG Maker VX Ace, make sure you have "Game > Show Console" enabled from the editor -- without the console open, this script does nothing in versions < 1.2, and hangs in versions > 1.3.

Essentially, this script operates entirely within the RGSS Console window that Ace opens with your game in test-play mode -- without access to that console window, it does nothing.

(I should probably add the "does nothing if there is no console" functionality back in, though, now that you mention it.)

**Comment by Malcanteth** [comment]
Thank you for this explanation. I missed the "enable option".

**Comment by Malcanteth** [comment]
Also there are a lot of useful macros mentioned in branch gh-pages, but none of them are seemed to exist neither in repo nor in downloads. Can I find them anywhere?

**Comment by Solistra** [comment]
The release with the most complete macro package is version 1.3 -- you can find the package on the Releases page as `macro_package.zip`. Make sure to extract the contents to your configured `MACRO_DIR` directory if you want to make use of them.
